// app/layout.tsx
import { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import ParticlesComponent from "@/components/particles-background/particles-background";

export const metadata: Metadata = {
  title: "Urfan Karimli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link  href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"
        />
      </head>
      <body className="font-roboto">
        <Header />
        <main className="min-h-[90vh] relative">
          {children}
          <ParticlesComponent />
        </main>
      </body>
    </html>
  );
}
